import { useState, useCallback, useRef, useEffect, useMemo } from "react";

// ══════ BIG-M SIMPLEX LP ══════
function linprog(c,A,b,bounds){var m=A.length,nO=c.length;var lb=bounds.map(function(x){return x[0]||0;});var ub=bounds.map(function(x){return(x[1]!=null&&x[1]<1e20)?x[1]:1e30;});var bS=new Float64Array(m);for(var i=0;i<m;i++){bS[i]=b[i];for(var j=0;j<nO;j++)bS[i]-=A[i][j]*lb[j];}var ubR=[];for(var j=0;j<nO;j++)if(ub[j]<1e29){var r=new Array(nO).fill(0);r[j]=1;ubR.push({r:r,rhs:ub[j]-lb[j]});}var M=m+ubR.length;var bA=new Float64Array(M);var AA=[];for(var i=0;i<m;i++){bA[i]=bS[i];AA.push(A[i].slice());}for(var e=0;e<ubR.length;e++){bA[m+e]=ubR[e].rhs;AA.push(ubR[e].r.slice());}var nArt=0;for(var i=0;i<M;i++)if(bA[i]<-1e-15)nArt++;var nS=M,nV=nO+nS+nArt,BM=1e8;var tab=[];var basis=new Int32Array(M);var ai=0;for(var i=0;i<M;i++){var row=new Float64Array(nV+1);if(bA[i]<-1e-15){for(var j=0;j<nO;j++)row[j]=-AA[i][j];row[nO+i]=-1;row[nO+nS+ai]=1;row[nV]=-bA[i];basis[i]=nO+nS+ai;ai++;}else{for(var j=0;j<nO;j++)row[j]=AA[i][j];row[nO+i]=1;row[nV]=bA[i];basis[i]=nO+i;}tab.push(row);}var obj=new Float64Array(nV+1);for(var j=0;j<nO;j++)obj[j]=c[j];for(var a=0;a<nArt;a++)obj[nO+nS+a]=BM;for(var i=0;i<M;i++)if(basis[i]>=nO+nS){for(var j=0;j<=nV;j++)obj[j]-=BM*tab[i][j];}for(var it=0;it<15000;it++){var pC=-1,best=-1e-10;for(var j=0;j<nV;j++)if(obj[j]<best){best=obj[j];pC=j;}if(pC<0)break;var pR=-1,minR=Infinity;for(var i=0;i<M;i++)if(tab[i][pC]>1e-12){var r=tab[i][nV]/tab[i][pC];if(r<minR-1e-12){minR=r;pR=i;}}if(pR<0)break;var pv=tab[pR][pC];for(var j=0;j<=nV;j++)tab[pR][j]/=pv;for(var i=0;i<M;i++){if(i===pR)continue;var f=tab[i][pC];if(Math.abs(f)<1e-15)continue;for(var j=0;j<=nV;j++)tab[i][j]-=f*tab[pR][j];}var f2=obj[pC];for(var j=0;j<=nV;j++)obj[j]-=f2*tab[pR][j];basis[pR]=pC;}var ok=true;for(var i=0;i<M;i++)if(basis[i]>=nO+nS&&tab[i][nV]>1e-6)ok=false;var x=new Float64Array(nO);for(var i=0;i<M;i++)if(basis[i]<nO)x[basis[i]]=Math.max(0,tab[i][nV]);for(var j=0;j<nO;j++)x[j]+=lb[j];return{x:x,ok:ok};}
function deaCRS(X,Y){var n=X.length,m=X[0].length,s=Y[0].length,eff=new Float64Array(n);for(var i=0;i<n;i++){var nv=1+n,cc=new Array(nv).fill(0);cc[0]=1;var AA=[],bb=[];for(var k=0;k<m;k++){var r=new Array(nv).fill(0);r[0]=-X[i][k];for(var j=0;j<n;j++)r[1+j]=X[j][k];AA.push(r);bb.push(0);}for(var l=0;l<s;l++){var r=new Array(nv).fill(0);for(var j=0;j<n;j++)r[1+j]=-Y[j][l];AA.push(r);bb.push(-Y[i][l]);}var bnd=[[0,1]];for(var j=0;j<n;j++)bnd.push([0,null]);var res=linprog(cc,AA,bb,bnd);eff[i]=res.ok?Math.max(Math.min(res.x[0],1),0):1;if(isNaN(eff[i]))eff[i]=1;}return eff;}
function deaVRS(X,Y){var n=X.length,m=X[0].length,s=Y[0].length,eff=new Float64Array(n);for(var i=0;i<n;i++){var nv=1+n,cc=new Array(nv).fill(0);cc[0]=1;var AA=[],bb=[];for(var k=0;k<m;k++){var r=new Array(nv).fill(0);r[0]=-X[i][k];for(var j=0;j<n;j++)r[1+j]=X[j][k];AA.push(r);bb.push(0);}for(var l=0;l<s;l++){var r=new Array(nv).fill(0);for(var j=0;j<n;j++)r[1+j]=-Y[j][l];AA.push(r);bb.push(-Y[i][l]);}var r1=new Array(nv).fill(0);for(var j=0;j<n;j++)r1[1+j]=1;AA.push(r1);bb.push(1);var r2=new Array(nv).fill(0);for(var j=0;j<n;j++)r2[1+j]=-1;AA.push(r2);bb.push(-1);var bnd=[[0,1]];for(var j=0;j<n;j++)bnd.push([0,null]);var res=linprog(cc,AA,bb,bnd);eff[i]=res.ok?Math.max(Math.min(res.x[0],1),0):1;if(isNaN(eff[i]))eff[i]=1;}return eff;}
function superEffCRS(X,Y,idx){var n=X.length,m=X[0].length,s=Y[0].length;var Xr=[],Yr=[];for(var j=0;j<n;j++)if(j!==idx){Xr.push(X[j]);Yr.push(Y[j]);}var nr=Xr.length;if(nr<2)return 1;var nv=1+nr,cc=new Array(nv).fill(0);cc[0]=1;var AA=[],bb=[];for(var k=0;k<m;k++){var r=new Array(nv).fill(0);r[0]=-X[idx][k];for(var j=0;j<nr;j++)r[1+j]=Xr[j][k];AA.push(r);bb.push(0);}for(var l=0;l<s;l++){var r=new Array(nv).fill(0);for(var j=0;j<nr;j++)r[1+j]=-Yr[j][l];AA.push(r);bb.push(-Y[idx][l]);}var bnd=[[0,10]];for(var j=0;j<nr;j++)bnd.push([0,null]);var res=linprog(cc,AA,bb,bnd);return res.ok?Math.max(res.x[0],0):NaN;}

// ══════ FILE PARSERS ══════
function parseCSV(text){var lines=text.split(/\r?\n/).filter(function(l){return l.trim();});if(lines.length<2)return{headers:[],data:[]};var d=lines[0].includes('\t')?'\t':(lines[0].split(',').length>lines[0].split(';').length?',':';');var sp=function(line){var res=[];var c='';var q=false;for(var ci=0;ci<line.length;ci++){var ch=line[ci];if(ch==='"'){q=!q;continue;}if(ch===d&&!q){res.push(c.trim());c='';continue;}c+=ch;}res.push(c.trim());return res;};var rawH=sp(lines[0]);var seen={};var headers=rawH.map(function(h,i){var name=h.replace(/^"|"$/g,'').trim();if(!name)name='col_'+i;if(seen[name]){seen[name]++;name=name+'_'+seen[name];}else seen[name]=1;return name;});var data=[];for(var i=1;i<lines.length;i++){var v=sp(lines[i]);if(v.length<2)continue;var row={};for(var j=0;j<headers.length;j++){var s=(v[j]||'').replace(/^"|"$/g,'');var n=parseFloat(s);row[headers[j]]=(s!==''&&!isNaN(n))?n:s;}data.push(row);}return{headers:headers,data:data};}
function parseJSON(text){try{var a=JSON.parse(text);if(!Array.isArray(a)){if(a.data&&Array.isArray(a.data))a=a.data;else a=[a];}if(!a.length)return{headers:[],data:[]};var h=Object.keys(a[0]);return{headers:h,data:a.map(function(row){var r={};h.forEach(function(k){var v=row[k];var n=typeof v==='number'?v:parseFloat(v);r[k]=typeof v==='number'?v:(!isNaN(n)&&String(v).trim()!=='')?n:(v||'');});return r;})};}catch(e){return{headers:[],data:[]};}}
function parseExcel(buffer,sheet){var XL=window.XLSX;if(!XL)throw new Error("Excel library loading");var wb=XL.read(buffer,{type:'array',cellDates:true});var nm=sheet||wb.SheetNames[0];var ws=wb.Sheets[nm];if(!ws)throw new Error('Sheet not found');var json=XL.utils.sheet_to_json(ws,{defval:null,raw:true});if(!json.length)return{headers:[],data:[],sheets:wb.SheetNames};var hdrSet={};var hdrOrder=[];for(var ri=0;ri<json.length;ri++){var keys=Object.keys(json[ri]);for(var ki=0;ki<keys.length;ki++){if(!hdrSet[keys[ki]]){hdrSet[keys[ki]]=true;hdrOrder.push(keys[ki]);}}}var seen={};var finalH=[];for(var i=0;i<hdrOrder.length;i++){var name=hdrOrder[i];if(seen[name]){seen[name]++;name=name+'_'+seen[name];}else seen[name]=1;finalH.push(name);}var data=json.map(function(row){var r={};for(var i=0;i<finalH.length;i++){var k=hdrOrder[i];var fk=finalH[i];var v=row[k];if(v instanceof Date)v=v.toISOString().slice(0,10);if(v==null||v===''){r[fk]=null;continue;}var n=typeof v==='number'?v:parseFloat(v);r[fk]=typeof v==='number'?v:(!isNaN(n)&&String(v).trim()!=='')?n:String(v);}return r;});return{headers:finalH,data:data,sheets:wb.SheetNames};}
function parseDTA(buf){var ab=buf.buffer.slice(buf.byteOffset,buf.byteOffset+buf.byteLength);var dv=new DataView(ab);var pos=0;var LE=true;var first=dv.getUint8(0);if(first===60){return parseDTA_new(ab,dv);}var ver=first;if(ver<102||ver>115)throw new Error('Unsupported Stata version ('+ver+'). Export as CSV.');pos=1;var byteord=dv.getUint8(pos);pos++;LE=(byteord!==1);pos++;pos++;function ri16(){var v=dv.getInt16(pos,LE);pos+=2;return v;}function ri32(){var v=dv.getInt32(pos,LE);pos+=4;return v;}function rf32(){var v=dv.getFloat32(pos,LE);pos+=4;return v;}function rf64(){var v=dv.getFloat64(pos,LE);pos+=8;return v;}function ru8(){return dv.getUint8(pos++);}function rstr(len){var s='';for(var i=0;i<len;i++){var c=dv.getUint8(pos+i);if(c===0)break;s+=String.fromCharCode(c);}pos+=len;return s;}var nvar=ri16();var nobs=ri32();if(ver>=105){pos+=81+18;}else{pos+=32+18;}var types=[];for(var i=0;i<nvar;i++)types.push(ru8());var nameLen=(ver>=110)?33:9;var names=[];for(var i=0;i<nvar;i++)names.push(rstr(nameLen));pos+=(nvar+1)*2;var fmtLen=(ver>=114)?49:(ver>=105?12:7);pos+=nvar*fmtLen;var lblLen=(ver>=110)?33:9;pos+=nvar*lblLen;pos+=nvar*81;if(ver>=105){while(pos<dv.byteLength-5){var etype=ru8();var elen=ri32();if(etype===0&&elen===0)break;pos+=elen;}}function normalizeType(t){if(ver>=111){if(t>=1&&t<=244)return{kind:'str',len:t};if(t===251)return{kind:'byte',len:1};if(t===252)return{kind:'int',len:2};if(t===253)return{kind:'long',len:4};if(t===254)return{kind:'float',len:4};if(t===255)return{kind:'double',len:8};}else{if(t>=1&&t<=80)return{kind:'str',len:t};if(t===98)return{kind:'byte',len:1};if(t===105)return{kind:'int',len:2};if(t===108)return{kind:'long',len:4};if(t===102)return{kind:'float',len:4};if(t===100)return{kind:'double',len:8};}return{kind:'byte',len:1};}var ntypes=types.map(normalizeType);var data=[];for(var obs=0;obs<nobs;obs++){if(pos>=dv.byteLength)break;var row={};for(var v=0;v<nvar;v++){var nt=ntypes[v];var val;if(nt.kind==='str'){val=rstr(nt.len);}else if(nt.kind==='byte'){val=dv.getInt8(pos);pos+=1;if(val>100||val<-127)val=null;}else if(nt.kind==='int'){val=ri16();if(val>32740||val<-32767)val=null;}else if(nt.kind==='long'){val=ri32();if(val>2147483620||val<-2147483647)val=null;}else if(nt.kind==='float'){val=rf32();if(!isFinite(val)||Math.abs(val)>1.7e38)val=null;}else if(nt.kind==='double'){val=rf64();if(!isFinite(val)||Math.abs(val)>8.9e307)val=null;}else{val=null;pos+=1;}row[names[v]]=val;}data.push(row);}return{headers:names,data:data};}
function parseDTA_new(ab,dv){var bytes=new Uint8Array(ab);var pos=0;var LE=true;function ru8(){return dv.getUint8(pos++);}function ri16(){var v=dv.getInt16(pos,LE);pos+=2;return v;}function ru16(){var v=dv.getUint16(pos,LE);pos+=2;return v;}function ri32(){var v=dv.getInt32(pos,LE);pos+=4;return v;}function rf32(){var v=dv.getFloat32(pos,LE);pos+=4;return v;}function rf64(){var v=dv.getFloat64(pos,LE);pos+=8;return v;}function rstr(len){var s='';for(var i=0;i<len;i++){var c=dv.getUint8(pos+i);if(c===0)break;s+=String.fromCharCode(c);}pos+=len;return s;}function seekTag(tag){var needle='<'+tag+'>';var nb=[];for(var i=0;i<needle.length;i++)nb.push(needle.charCodeAt(i));for(var i=pos;i<bytes.length-nb.length;i++){var ok=true;for(var j=0;j<nb.length;j++){if(bytes[i+j]!==nb[j]){ok=false;break;}}if(ok){pos=i+nb.length;return true;}}return false;}seekTag('stata_dta');seekTag('header');seekTag('release');var relStr=rstr(10).replace(/[^0-9]/g,'');var rel=parseInt(relStr)||117;seekTag('byteorder');var boStr=rstr(3);LE=(boStr==='LSF');seekTag('K');var nvar=rel>=119?ri32():ru16();seekTag('N');var nobs;if(rel>=118){var lo=dv.getUint32(pos,LE);var hi=dv.getUint32(pos+4,LE);nobs=LE?(hi*4294967296+lo):(lo*4294967296+hi);pos+=8;}else{nobs=ri32();}seekTag('label');seekTag('timestamp');seekTag('variable_types');var types=[];for(var i=0;i<nvar;i++)types.push(ru16());seekTag('varnames');var nameLen=(rel>=118)?129:33;var names=[];for(var i=0;i<nvar;i++)names.push(rstr(nameLen));seekTag('data');var data=[];for(var obs=0;obs<nobs&&obs<500000;obs++){if(pos>=dv.byteLength-2)break;var row={};for(var v=0;v<nvar;v++){var typ=types[v];var val;if(typ<=2045){val=rstr(typ);}else if(typ===65526){val=rf64();if(!isFinite(val)||Math.abs(val)>8.9e307)val=null;}else if(typ===65527){val=rf32();if(!isFinite(val)||Math.abs(val)>1.7e38)val=null;}else if(typ===65528){val=ri32();if(val>2147483620||val<-2147483647)val=null;}else if(typ===65529){val=ri16();if(val>32740||val<-32767)val=null;}else if(typ===65530){val=ru8();if(val>100)val=null;}else if(typ===32768){pos+=(rel>=118?8:8);val='(strL)';}else{val=null;}row[names[v]]=val;}data.push(row);}return{headers:names,data:data};}
var EXT=function(n){return(n||'').split('.').pop().toLowerCase();};
function calcStats(arr){var v=arr.filter(function(x){return x!=null&&!isNaN(x)&&isFinite(x);}).sort(function(a,b){return a-b;});if(!v.length)return null;var n=v.length,mean=v.reduce(function(s,x){return s+x;},0)/n;var sd=Math.sqrt(v.reduce(function(s,x){return s+(x-mean)*(x-mean);},0)/Math.max(n-1,1));var pct=function(p){var i=p*(n-1),lo=Math.floor(i),hi=Math.ceil(i);return lo===hi?v[lo]:v[lo]*(hi-i)+v[hi]*(i-lo);};var nEff=v.filter(function(x){return Math.abs(x-1)<1e-4;}).length;return{n:n,mean:mean,sd:sd,min:v[0],p25:pct(.25),median:pct(.5),p75:pct(.75),max:v[n-1],nEff:nEff,pctEff:100*nEff/n};}
function computeAll(valid,X,Y,inpV,outV,grpV,optV,numH,effCRS,effVRS){var n=valid.length;var scaleEff=new Float64Array(n);for(var i=0;i<n;i++)scaleEff[i]=effVRS[i]>1e-10?effCRS[i]/effVRS[i]:NaN;var excess={},pctExcess={},targets={};inpV.forEach(function(v){excess[v]=new Float64Array(n);pctExcess[v]=new Float64Array(n);targets[v]=new Float64Array(n);});for(var i=0;i<n;i++)inpV.forEach(function(v,k){targets[v][i]=effCRS[i]*X[i][k];excess[v][i]=X[i][k]-targets[v][i];pctExcess[v][i]=X[i][k]>1e-10?excess[v][i]/X[i][k]*100:0;});var groupRes={};grpV.forEach(function(gv){var g={};valid.forEach(function(r,i){var k=String(r[gv]!=null?r[gv]:'N/A');if(!g[k])g[k]=[];g[k].push(i);});groupRes[gv]=Object.entries(g).map(function(e){var s2=calcStats(e[1].map(function(i){return effCRS[i];}));return s2?{group:e[0],n:s2.n,mean:s2.mean,sd:s2.sd,min:s2.min,median:s2.median,max:s2.max,nEff:s2.nEff,pctEff:s2.pctEff}:null;}).filter(Boolean);});var slackGrp={};grpV.forEach(function(gv){var g={};valid.forEach(function(r,i){var k=String(r[gv]!=null?r[gv]:'N/A');if(!g[k])g[k]=[];g[k].push(i);});var rows=[];inpV.forEach(function(inp){Object.entries(g).forEach(function(e){var exV=e[1].map(function(i){return pctExcess[inp][i];}).filter(function(v){return v>0.01;});rows.push({input:inp,group:e[0],nSchools:e[1].length,nWithExcess:exV.length,pctWithExcess:e[1].length?+(100*exV.length/e[1].length).toFixed(1):0,meanExcessPct:exV.length?+(exV.reduce(function(a,b){return a+b;},0)/exV.length).toFixed(1):0});});});slackGrp[gv]=rows;});var optimRes={};optV.forEach(function(ov){if(!numH.includes(ov))return;var vals=valid.map(function(r,i){return{act:r[ov],tgt:effCRS[i]*r[ov],exc:r[ov]-effCRS[i]*r[ov]};}).filter(function(v){return!isNaN(v.act)&&isFinite(v.act);});var tA=vals.reduce(function(s,v){return s+v.act;},0),tT=vals.reduce(function(s,v){return s+v.tgt;},0),tE=vals.reduce(function(s,v){return s+Math.max(0,v.exc);},0),nE=vals.filter(function(v){return v.exc>0.01;}).length;optimRes[ov]={totalActual:tA,totalTarget:tT,totalExcess:tE,nWithExcess:nE,n:vals.length,pctWithExcess:100*nE/vals.length};});var schoolData=valid.map(function(row,i){var obj={};Object.keys(row).forEach(function(k){obj[k]=row[k];});obj.eff_crs=effCRS[i];obj.eff_vrs=effVRS[i];obj.scale_eff=scaleEff[i];inpV.forEach(function(v){obj["pct_excess_"+v]=pctExcess[v][i];obj["target_"+v]=targets[v][i];});return obj;});return{n:n,m:inpV.length,s:outV.length,effCRS:Array.from(effCRS),effVRS:Array.from(effVRS),scaleEff:Array.from(scaleEff),crsSt:calcStats(Array.from(effCRS)),vrsSt:calcStats(Array.from(effVRS)),excess:excess,pctExcess:pctExcess,targets:targets,groupRes:groupRes,slackGrp:slackGrp,optimRes:optimRes,schoolData:schoolData,inputVars:inpV.slice(),outputVars:outV.slice(),groupVars:grpV.slice(),optimVars:optV.slice()};}

// ══════ UI COMPONENTS ══════
function Hist({values,title,color,h}){var cl=color||"#4f46e5";var ht=h||175;var valid=(values||[]).filter(function(v){return v!=null&&!isNaN(v)&&isFinite(v);});if(!valid.length)return null;var bins=14,mn=Math.min.apply(null,valid),mx=Math.max.apply(null,valid),rng=mx-mn||1;var bw=rng/bins,counts=new Array(bins).fill(0);valid.forEach(function(v){counts[Math.min(Math.floor((v-mn)/bw),bins-1)]++;});var maxC=Math.max.apply(null,counts.concat([1])),W=480,barW=(W-60)/bins;return (<div style={{marginBottom:20}}><div style={{fontSize:13,fontWeight:600,color:"#1a1d29",marginBottom:8}}>{title}</div><svg width={W} height={ht+30} style={{display:'block'}}>{counts.map(function(c,i){var bh=(c/maxC)*(ht-20),x=40+i*barW;return (<g key={i}><rect x={x} y={ht-bh} width={barW-2} height={bh} rx={2} fill={cl} opacity={0.85}/>{c>0&&<text x={x+barW/2} y={ht-bh-3} textAnchor="middle" fontSize={8} fill="#6b7194">{c}</text>}</g>);})}<line x1={38} y1={ht} x2={W} y2={ht} stroke="#e2e5f1"/><text x={42} y={ht+13} fontSize={8} fill="#6b7194">{mn.toFixed(2)}</text><text x={W-10} y={ht+13} fontSize={8} fill="#6b7194" textAnchor="end">{mx.toFixed(2)}</text></svg></div>);}
function BarChart({data,xKey,yKey,title,color,h}){var cl=color||"#4f46e5";var ht=h||200;if(!data||!data.length)return null;var maxV=Math.max.apply(null,data.map(function(d){return d[yKey]||0;}).concat([0.001]));var barW=Math.max(22,Math.min(55,460/data.length));var W=Math.max(460,data.length*(barW+8)+70);return (<div style={{marginBottom:20}}><div style={{fontSize:13,fontWeight:600,color:"#1a1d29",marginBottom:8}}>{title}</div><div style={{overflowX:'auto'}}><svg width={W} height={ht+50}>{data.map(function(d,i){var v=d[yKey]||0,bh=(v/maxV)*(ht-20),x=50+i*(barW+8);return (<g key={i}><rect x={x} y={ht-bh} width={barW} height={bh} rx={3} fill={cl} opacity={0.85}/><text x={x+barW/2} y={ht-bh-4} textAnchor="middle" fontSize={9} fill="#6b7194">{typeof v==='number'?v.toFixed(3):v}</text><text x={x+barW/2} y={ht+12} textAnchor="middle" fontSize={8} fill="#6b7194" transform={"rotate(-30,"+(x+barW/2)+","+(ht+12)+")"}>{String(d[xKey]).slice(0,14)}</text></g>);})}<line x1={46} y1={ht} x2={W} y2={ht} stroke="#e2e5f1"/></svg></div></div>);}
function Tbl({columns,data,pp}){var perPage=pp||18;var[pg,setPg]=useState(0);var pages=Math.ceil(data.length/perPage);var slice=data.slice(pg*perPage,(pg+1)*perPage);return (<div style={{overflowX:'auto',marginBottom:14}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:12,fontFamily:'monospace'}}><thead><tr>{columns.map(function(c,i){return (<th key={i} style={{padding:'8px 10px',background:'#2E5090',color:'#fff',fontWeight:600,textAlign:'left',whiteSpace:'nowrap',fontSize:11}}>{c.label||c.key}</th>);})}</tr></thead><tbody>{slice.map(function(row,ri){return (<tr key={ri} style={{background:ri%2===0?'#fff':'#f3f4f8'}}>{columns.map(function(c,ci){var val=row[c.key];var dec=c.dec!=null?c.dec:3;return (<td key={ci} style={{padding:'6px 10px',borderBottom:'1px solid #e2e5f1',whiteSpace:'nowrap'}}>{typeof val==='number'?val.toFixed(dec):(val!=null?val:'')}</td>);})}</tr>);})}</tbody></table>{pages>1&&(<div style={{display:'flex',gap:6,marginTop:8,alignItems:'center',justifyContent:'center'}}><button onClick={function(){setPg(Math.max(0,pg-1));}} disabled={pg===0} style={{padding:'4px 12px',borderRadius:6,border:'1px solid #e2e5f1',background:'#fff',cursor:'pointer',fontSize:11,opacity:pg===0?0.4:1}}>Prev</button><span style={{fontSize:12,color:'#6b7194'}}>Page {pg+1} of {pages}</span><button onClick={function(){setPg(Math.min(pages-1,pg+1));}} disabled={pg>=pages-1} style={{padding:'4px 12px',borderRadius:6,border:'1px solid #e2e5f1',background:'#fff',cursor:'pointer',fontSize:11,opacity:pg>=pages-1?0.4:1}}>Next</button></div>)}</div>);}
function Card({children,style}){return (<div style={Object.assign({background:'#fff',borderRadius:16,padding:20,boxShadow:'0 1px 3px rgba(0,0,0,0.06),0 4px 12px rgba(0,0,0,0.04)',border:'1px solid #e2e5f1'},style||{})}>{children}</div>);}
function MetricCard({icon,label,value,color}){return (<div style={{background:'#fff',borderRadius:12,padding:'16px 18px',boxShadow:'0 1px 3px rgba(0,0,0,0.06)',border:'1px solid #e2e5f1',borderLeft:"4px solid "+(color||'#4f46e5')}}><div style={{fontSize:20,marginBottom:6}}>{icon}</div><div style={{fontSize:11,color:'#6b7194',marginBottom:4}}>{label}</div><div style={{fontSize:20,fontWeight:700,fontFamily:"monospace"}}>{value}</div></div>);}
function SectionLabel({text,color}){return (<div style={{fontSize:13,fontWeight:700,color:color||'#1a1d29',marginBottom:8,marginTop:16,padding:'6px 12px',borderLeft:'4px solid '+(color||'#4f46e5'),background:(color||'#4f46e5')+'0a'}}>{text}</div>);}
var statRows=function(st){if(!st)return[];return[{s:'N',v:st.n},{s:'Mean',v:st.mean},{s:'SD',v:st.sd},{s:'Min',v:st.min},{s:'P25',v:st.p25},{s:'Median',v:st.median},{s:'P75',v:st.p75},{s:'Max',v:st.max},{s:'N Efficient',v:st.nEff},{s:'% Efficient',v:st.pctEff}];};
function ResultBlock({r,color}){if(!r)return null;return (<div><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:12,marginBottom:16}}><MetricCard icon="📐" label="Observations" value={r.n} color={color}/><MetricCard icon="⚙️" label="In x Out" value={r.m+" x "+r.s} color="#0891b2"/><MetricCard icon="📊" label="Mean CRS" value={r.crsSt?r.crsSt.mean.toFixed(3):'-'} color="#059669"/><MetricCard icon="⭐" label="Efficient" value={r.crsSt?(r.crsSt.nEff+" ("+r.crsSt.pctEff.toFixed(1)+"%)"):'-'} color="#d97706"/></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:14}}><Card><h3 style={{margin:'0 0 10px',fontSize:14}}>CRS Efficiency</h3><Tbl columns={[{key:'s',label:'Statistic'},{key:'v',label:'Value',dec:4}]} data={statRows(r.crsSt)}/></Card><Card><h3 style={{margin:'0 0 10px',fontSize:14}}>VRS Efficiency</h3><Tbl columns={[{key:'s',label:'Statistic'},{key:'v',label:'Value',dec:4}]} data={statRows(r.vrsSt)}/></Card></div></div>);}
function EffBlock({r,hdr,numH}){if(!r)return null;return (<div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:14}}><Card><Hist values={r.effCRS} title="CRS Distribution" color="#4f46e5"/></Card><Card><Hist values={r.effVRS} title="VRS Distribution" color="#059669"/></Card><Card><Hist values={r.scaleEff.filter(function(v){return isFinite(v);})} title="Scale Efficiency" color="#d97706"/></Card><Card><div style={{fontSize:13,fontWeight:600,marginBottom:8}}>CRS vs VRS</div><svg width={280} height={280} style={{display:'block',margin:'0 auto'}}><line x1={35} y1={250} x2={265} y2={250} stroke="#e2e5f1"/><line x1={35} y1={250} x2={35} y2={15} stroke="#e2e5f1"/><line x1={35} y1={15} x2={265} y2={250} stroke="#dc2626" strokeWidth={1} strokeDasharray="4,3" opacity={0.4}/>{r.effCRS.slice(0,300).map(function(c,i){var v=r.effVRS[i];if(!isFinite(c)||!isFinite(v))return null;return (<circle key={i} cx={35+c*230} cy={250-v*230} r={3} fill="#4f46e5" opacity={0.5}/>);})}<text x={150} y={270} textAnchor="middle" fontSize={10} fill="#6b7194">CRS</text><text x={12} y={132} textAnchor="middle" fontSize={10} fill="#6b7194" transform="rotate(-90,12,132)">VRS</text></svg></Card></div><Card style={{marginTop:14}}><h3 style={{margin:'0 0 10px',fontSize:14}}>Bottom 10</h3><Tbl columns={hdr.filter(function(h){return !numH.includes(h);}).slice(0,2).map(function(h){return{key:h,label:h};}).concat([{key:'eff_crs',label:'CRS',dec:4},{key:'eff_vrs',label:'VRS',dec:4},{key:'scale_eff',label:'Scale',dec:4}]).concat(r.inputVars.map(function(v){return{key:'pct_excess_'+v,label:'%Exc '+v.slice(0,14),dec:1};}))} data={r.schoolData.slice().sort(function(a,b){return a.eff_crs-b.eff_crs;}).slice(0,10)}/></Card></div>);}
function DisaggBlock({r}){if(!r||!r.groupVars.length)return (<Card style={{textAlign:'center',padding:30}}><p style={{color:'#6b7194'}}>No disaggregation variables.</p></Card>);return (<div>{r.groupVars.map(function(gv){return (<Card key={gv} style={{marginBottom:14}}><h3 style={{margin:'0 0 12px',fontSize:15}}>By {gv}</h3>{r.groupRes[gv]&&<div><BarChart data={r.groupRes[gv]} xKey="group" yKey="mean" title={"Mean CRS by "+gv}/><Tbl columns={[{key:'group',label:gv},{key:'n',label:'N',dec:0},{key:'mean',label:'Mean',dec:3},{key:'sd',label:'SD',dec:3},{key:'min',label:'Min',dec:3},{key:'median',label:'Median',dec:3},{key:'max',label:'Max',dec:3},{key:'nEff',label:'Eff',dec:0},{key:'pctEff',label:'%Eff',dec:1}]} data={r.groupRes[gv]}/></div>}{r.slackGrp[gv]&&<div><h4 style={{margin:'14px 0 6px',fontSize:12,fontWeight:600,color:'#6b7194'}}>Input Excess by {gv}</h4><Tbl columns={[{key:'input',label:'Input'},{key:'group',label:gv},{key:'nSchools',label:'N',dec:0},{key:'nWithExcess',label:'W/Exc',dec:0},{key:'pctWithExcess',label:'%',dec:1},{key:'meanExcessPct',label:'Mean%',dec:1}]} data={r.slackGrp[gv]}/></div>}</Card>);})}</div>);}
function SlackBlock({r}){if(!r)return null;return (<div><Card style={{marginBottom:14}}><h3 style={{margin:'0 0 12px',fontSize:15}}>Input Excess Prevalence</h3><p style={{fontSize:11,color:'#6b7194',margin:'0 0 12px',fontStyle:'italic'}}>Note: % excess is proportional (1-theta) and equal across inputs in Stage 1 DEA. Absolute excess differs by variable scale.</p>{r.inputVars.map(function(inp){var exV=Array.from(r.pctExcess[inp]);var absV=Array.from(r.excess[inp]);var has=exV.filter(function(v){return v>0.01;}).length;var mE=has>0?exV.filter(function(v){return v>0.01;}).reduce(function(a,b){return a+b;},0)/has:0;var mAbs=has>0?absV.filter(function(v){return v>0.001;}).reduce(function(a,b){return a+b;},0)/has:0;var meanActual=0;for(var i=0;i<r.n;i++)meanActual+=r.schoolData[i][inp]||0;meanActual=meanActual/r.n;var meanTarget=meanActual*r.crsSt.mean;return (<div key={inp} style={{marginBottom:12,padding:12,background:'#f3f4f8',borderRadius:10}}><div style={{display:'flex',justifyContent:'space-between',marginBottom:4}}><span style={{fontWeight:600,fontSize:12}}>{inp}</span><span style={{fontSize:11,color:'#6b7194'}}>{has}/{r.n} ({(100*has/r.n).toFixed(1)}%) with excess</span></div><div style={{height:8,background:'#e2e5f1',borderRadius:4,overflow:'hidden'}}><div style={{height:'100%',width:(100*has/r.n)+'%',background:'linear-gradient(90deg,#f59e0b,#ef4444)',borderRadius:4}}/></div><div style={{display:'flex',gap:16,marginTop:6,fontSize:11,color:'#6b7194'}}><span>Mean actual: {meanActual.toFixed(4)}</span><span>Mean target: {meanTarget.toFixed(4)}</span><span>Mean abs. excess: {mAbs.toFixed(4)}</span><span>Mean % excess: {mE.toFixed(1)}%</span></div></div>);})}</Card><Card><h3 style={{margin:'0 0 12px',fontSize:14}}>Excess Distributions (absolute)</h3><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:14}}>{r.inputVars.map(function(inp){return (<Hist key={inp} values={Array.from(r.excess[inp]).filter(function(v){return v>0.001;})} title={"Absolute Excess: "+inp} color="#ef4444"/>);})}</div></Card></div>);}
function OptimBlock({r}){if(!r||!r.optimVars.length)return (<Card style={{textAlign:'center',padding:30}}><p style={{color:'#6b7194'}}>No optimization variables.</p></Card>);return (<div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:14}}>{r.optimVars.map(function(ov){var o=r.optimRes[ov];if(!o)return null;var mA=o.totalActual/o.n;var mT=o.totalTarget/o.n;var mE=o.totalExcess/o.n;var pctRed=mA>0?((mA-mT)/mA*100).toFixed(1):'0';return (<Card key={ov}><h3 style={{margin:'0 0 12px',fontSize:14}}>{ov}</h3><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8,marginBottom:12}}><div style={{background:'#f3f4f8',borderRadius:8,padding:10,textAlign:'center'}}><div style={{fontSize:10,color:'#6b7194'}}>MEAN ACTUAL</div><div style={{fontSize:15,fontWeight:700,fontFamily:'monospace'}}>{mA.toFixed(4)}</div></div><div style={{background:'#ecfdf5',borderRadius:8,padding:10,textAlign:'center'}}><div style={{fontSize:10,color:'#059669'}}>MEAN OPTIMAL</div><div style={{fontSize:15,fontWeight:700,fontFamily:'monospace',color:'#059669'}}>{mT.toFixed(4)}</div></div><div style={{background:'#fef2f2',borderRadius:8,padding:10,textAlign:'center'}}><div style={{fontSize:10,color:'#dc2626'}}>MEAN EXCESS</div><div style={{fontSize:15,fontWeight:700,fontFamily:'monospace',color:'#dc2626'}}>{mE.toFixed(4)}</div></div><div style={{background:'#fffbeb',borderRadius:8,padding:10,textAlign:'center'}}><div style={{fontSize:10,color:'#d97706'}}>AVG. REDUCTION</div><div style={{fontSize:15,fontWeight:700,fontFamily:'monospace',color:'#d97706'}}>{pctRed}%</div></div></div><div style={{fontSize:11,color:'#1a1d29',marginBottom:6}}>{o.nWithExcess} of {o.n} DMUs ({o.pctWithExcess.toFixed(1)}%) have excess. On average, inefficient DMUs could reduce {ov} by {pctRed}% to reach the frontier.</div><div style={{marginTop:8,padding:8,background:'#f8f9fc',borderRadius:6,fontSize:10,color:'#6b7194'}}>System totals (meaningful for absolute variables like n_teachers, grant_amount): Actual: {o.totalActual.toFixed(2)} · Optimal: {o.totalTarget.toFixed(2)} · Excess: {o.totalExcess.toFixed(2)}</div></Card>);})}</div>);}

// ══════ MAIN APP ══════
export default function App(){
  var[step,setStep]=useState(0);var[raw,setRaw]=useState(null);var[hdr,setHdr]=useState([]);var[srch,setSrch]=useState('');
  var[inpV,setInpV]=useState([]);var[outV,setOutV]=useState([]);var[grpV,setGrpV]=useState([]);var[optV,setOptV]=useState([]);
  var[doSE,setDoSE]=useState(false);var[seTh,setSeTh]=useState(1.5);var[cleanCutoff,setCleanCutoff]=useState(1.5);
  var[res,setRes]=useState(null);var[prog,setProg]=useState('');var[tab,setTab]=useState('summary');
  var[fName,setFName]=useState('');var[fErr,setFErr]=useState('');var[fLoad,setFLoad]=useState(false);
  var[sheets,setSheets]=useState([]);var[selSh,setSelSh]=useState('');var[buf,setBuf]=useState(null);var[xlOk,setXlOk]=useState(false);
  var[filters,setFilters]=useState([]);var[commaInput,setCommaInput]=useState({inp:'',out:'',grp:'',opt:''});
  var[expandedSections,setExpandedSections]=useState({});var[inputMethod,setInputMethod]=useState('click');
  var fRef=useRef();

  useEffect(function(){if(window.XLSX){setXlOk(true);return;}var s=document.createElement('script');s.src='https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js';s.onload=function(){setXlOk(true);};document.head.appendChild(s);},[]);
  var commit=function(h,d){if(h.length&&d.length){setHdr(h);setRaw(d);setStep(1);setFErr('');}else setFErr('No valid data found.');setFLoad(false);};
  var handleFile=useCallback(function(file){if(!file)return;var ext=EXT(file.name);setFName(file.name);setFErr('');setFLoad(true);setSheets([]);setSelSh('');setBuf(null);
    if(ext==='json'){var r=new FileReader();r.onload=function(e){try{var p=parseJSON(e.target.result);commit(p.headers,p.data);}catch(er){setFErr(er.message);setFLoad(false);}};r.readAsText(file);}
    else if(ext==='dta'){var r=new FileReader();r.onload=function(e){try{var b=new Uint8Array(e.target.result);var p=parseDTA(b);commit(p.headers,p.data);}catch(er){setFErr('Stata error: '+er.message);setFLoad(false);}};r.readAsArrayBuffer(file);}
    else if(['xlsx','xls','ods','xlsm','xlsb'].indexOf(ext)>=0){if(!xlOk&&!window.XLSX){setFErr('Excel library loading.');setFLoad(false);return;}var r=new FileReader();r.onload=function(e){try{var b=new Uint8Array(e.target.result);var p=parseExcel(b,null);if(p.sheets&&p.sheets.length>1){setSheets(p.sheets);setSelSh(p.sheets[0]);setBuf(b);}commit(p.headers,p.data);}catch(er){setFErr('File error: '+er.message);setFLoad(false);}};r.readAsArrayBuffer(file);}
    else{var r=new FileReader();r.onload=function(e){try{var p=parseCSV(e.target.result);commit(p.headers,p.data);}catch(er){setFErr(er.message);setFLoad(false);}};r.readAsText(file);}
  },[xlOk]);
  var switchSh=useCallback(function(nm){if(!buf)return;setSelSh(nm);setFLoad(true);try{var p=parseExcel(buf,nm);commit(p.headers,p.data);}catch(er){setFErr(er.message);setFLoad(false);}},[buf]);
  var handleDrop=useCallback(function(e){e.preventDefault();handleFile(e.dataTransfer&&e.dataTransfer.files&&e.dataTransfer.files[0]);},[handleFile]);
  var numH=useMemo(function(){if(!raw||!raw.length)return[];return hdr.filter(function(h){var sample=raw.slice(0,Math.min(100,raw.length));var nonNull=sample.filter(function(r){return r[h]!=null&&r[h]!=='';});if(nonNull.length===0)return false;var numCount=nonNull.filter(function(r){return typeof r[h]==='number'&&!isNaN(r[h]);}).length;return numCount>nonNull.length*0.3;});},[hdr,raw]);
  var catH=useMemo(function(){return hdr.filter(function(h){return numH.indexOf(h)<0;});},[hdr,numH]);
  var filtH=useMemo(function(){if(!srch)return hdr;var q=srch.toLowerCase();return hdr.filter(function(h){return h.toLowerCase().indexOf(q)>=0;});},[hdr,srch]);
  var tog=function(v,list,setter){setter(function(prev){if(prev.indexOf(v)>=0){if(setter===setInpV)setOptV(function(ov){return ov.filter(function(x){return x!==v;});});return prev.filter(function(x){return x!==v;});}return prev.concat([v]);});};
  var uniqueVals=useCallback(function(v){if(!raw)return[];var s={};raw.forEach(function(r){if(r[v]!=null)s[String(r[v])]=true;});return Object.keys(s).sort();},[raw]);
  var filteredCount=useMemo(function(){if(!raw)return 0;var d=raw;filters.forEach(function(f){if(f.values.length>0)d=d.filter(function(r){return f.values.indexOf(String(r[f.variable]))>=0;});});return d.length;},[raw,filters]);
  var applyComma=function(text,setter,validList){var vars=text.split(',').map(function(s){return s.trim();}).filter(function(s){return s&&validList.indexOf(s)>=0;});if(vars.length>0)setter(function(prev){var newArr=prev.slice();vars.forEach(function(v){if(newArr.indexOf(v)<0)newArr.push(v);});return newArr;});};
  var canRun=inpV.length>0&&outV.length>0;

  var run=useCallback(function(){
    if(!canRun||!raw)return;setStep(2);setProg('Preparing...');
    setTimeout(function(){try{
      var filtered=raw;filters.forEach(function(f){if(f.values.length>0)filtered=filtered.filter(function(r){return f.values.indexOf(String(r[f.variable]))>=0;});});
      var needed=inpV.concat(outV);
      var nBefore=filtered.length;
      var valid=filtered.filter(function(row){
        return inpV.every(function(v){var val=row[v];return val!=null&&typeof val==='number'&&!isNaN(val)&&isFinite(val)&&val>0;})
          && outV.every(function(v){var val=row[v];return val!=null&&typeof val==='number'&&!isNaN(val)&&isFinite(val)&&val>=0;});
      });
      var nDropped=nBefore-valid.length;
      if(valid.length<5){setProg('Error: fewer than 5 valid observations (got '+valid.length+' from '+nBefore+', dropped '+nDropped+' with missing/invalid values).');return;}
      var n=valid.length;
      // Sort variables alphabetically so column order is always the same regardless of selection order
      var sortedInp=inpV.slice().sort();
      var sortedOut=outV.slice().sort();
      var X=valid.map(function(r){return sortedInp.map(function(v){return r[v];});});
      var Y=valid.map(function(r){return sortedOut.map(function(v){return r[v];});});
      setProg("CRS DEA on "+n+" DMUs ("+nDropped+" dropped for missing values)...");
      setTimeout(function(){try{
        var effCRS=deaCRS(X,Y);setProg('VRS DEA...');
        setTimeout(function(){try{
          var effVRS=deaVRS(X,Y);var fullRes=computeAll(valid,X,Y,sortedInp,sortedOut,grpV,optV,numH,effCRS,effVRS);
          var superRes=null,cleanRes=null;
          if(doSE){setProg('Super-efficiency...');var se=new Float64Array(n);var nEff=0;for(var i=0;i<n;i++){if(Math.abs(effCRS[i]-1)<1e-4){nEff++;se[i]=superEffCRS(X,Y,i);}else se[i]=effCRS[i];}var flagged=[],extreme=[];for(var i=0;i<n;i++){if(se[i]>seTh)extreme.push({idx:i,score:se[i],data:valid[i]});else if(se[i]>1.2)flagged.push({idx:i,score:se[i],data:valid[i]});}superRes={scores:se,nEfficient:nEff,flagged:flagged,extreme:extreme,threshold:seTh};
            var cutoff=cleanCutoff;var cV=[],cX=[],cY=[];for(var i=0;i<n;i++){if(se[i]<=cutoff||Math.abs(effCRS[i]-1)>=1e-4){cV.push(valid[i]);cX.push(X[i]);cY.push(Y[i]);}}
            if(cV.length>=5){setProg('Clean DEA...');var cc=deaCRS(cX,cY);var cv=deaVRS(cX,cY);cleanRes=computeAll(cV,cX,cY,sortedInp,sortedOut,grpV,optV,numH,cc,cv);cleanRes.nDropped=n-cV.length;}}
          setRes({full:fullRes,superRes:superRes,clean:cleanRes,hasSE:doSE,cutoff:cleanCutoff,nTotal:nBefore,nDroppedMissing:nDropped});setStep(3);setTab('summary');
        }catch(err){setProg('Error: '+err.message);}},50);
      }catch(err){setProg('Error: '+err.message);}},50);
    }catch(err){setProg('Error: '+err.message);}},80);
  },[canRun,raw,inpV,outV,grpV,optV,doSE,seTh,cleanCutoff,numH,filters]);

  var VarPill=function(p){return (<button onClick={p.onClick} style={{padding:'5px 12px',borderRadius:8,border:'1.5px solid '+(p.selected?p.color:'#e2e5f1'),background:p.selected?(p.color+'18'):'#fff',color:p.selected?p.color:'#1a1d29',fontSize:11,cursor:'pointer',fontWeight:p.selected?600:400}}>{p.label}</button>);};

  // Tag for selected variable (removable)
  var SelTag=function(p){return (<span style={{display:'inline-flex',alignItems:'center',gap:3,padding:'2px 8px 2px 10px',borderRadius:12,background:p.color+'18',color:p.color,fontSize:10,fontWeight:600}}>{p.name}<span onClick={p.onRemove} style={{cursor:'pointer',fontSize:13,lineHeight:1,opacity:0.6,marginLeft:2}}>x</span></span>);};

  return (
    <div style={{fontFamily:"'Segoe UI',system-ui,sans-serif",background:'#f8f9fc',minHeight:'100vh',color:'#1a1d29'}}>
      <style>{"@keyframes spin{to{transform:rotate(360deg)}} *{box-sizing:border-box}"}</style>

      {/* HEADER */}
      <header style={{background:'linear-gradient(135deg,#1e1b4b,#312e81,#4338ca)',padding:'28px 32px 20px',color:'#fff'}}>
        <div style={{maxWidth:1100,margin:'0 auto'}}>
          <h1 style={{margin:0,fontSize:24,fontWeight:800}}>DEA Analysis Platform</h1>
          <p style={{margin:'6px 0 0',fontSize:12,opacity:0.7,lineHeight:1.6}}>
            CRS Model (CCR): Charnes, Cooper, and Rhodes (1978) · VRS Model (BCC): Banker, Charnes, and Cooper (1984)<br/>
            Super-Efficiency: Andersen and Petersen (1993) · Stata DEA command: Ji and Lee (2010)
          </p>
          <p style={{margin:'4px 0 0',fontSize:11,opacity:0.45}}>Platform developed by Karina Acevedo Gonzalez @kacego9 · 2026</p>
        </div>
      </header>

      {/* STEPPER */}
      <div style={{maxWidth:1100,margin:'0 auto',padding:'20px 32px 0'}}><div style={{display:'flex',gap:4,marginBottom:24}}>{['Upload','Configure','Run','Results'].map(function(s,i){return (<div key={i} style={{flex:1,display:'flex',alignItems:'center',gap:8}}><div style={{width:28,height:28,borderRadius:'50%',display:'flex',alignItems:'center',justifyContent:'center',fontSize:12,fontWeight:600,background:step>=i?'#4f46e5':'#f3f4f8',color:step>=i?'#fff':'#6b7194'}}>{i+1}</div><span style={{fontSize:12,fontWeight:step===i?600:400,color:step>=i?'#1a1d29':'#6b7194'}}>{s}</span>{i<3&&<div style={{flex:1,height:2,background:step>i?'#4f46e5':'#e2e5f1'}}/>}</div>);})}</div></div>

      <div style={{maxWidth:1100,margin:'0 auto',padding:'0 32px 40px'}}>

        {/* ══════ UPLOAD ══════ */}
        {step===0&&(<Card style={{textAlign:'center',padding:40}}><div onDrop={handleDrop} onDragOver={function(e){e.preventDefault();}} style={{border:'2px dashed #e2e5f1',borderRadius:16,padding:36}}>
          <div style={{width:72,height:72,borderRadius:20,background:'#e0e7ff',display:'flex',alignItems:'center',justifyContent:'center',margin:'0 auto 20px',fontSize:32}}>📊</div>
          <h2 style={{margin:'0 0 8px',fontSize:22}}>Upload Your Dataset</h2>
          <p style={{color:'#6b7194',fontSize:14,margin:'0 0 24px'}}>Supports XLSX, XLS, CSV, TSV, ODS, JSON, TXT, DTA (Stata)</p>
          <div style={{display:'flex',flexWrap:'wrap',gap:6,justifyContent:'center',marginBottom:24}}>{['XLSX','XLS','CSV','TSV','ODS','JSON','TXT','DTA'].map(function(e){return (<span key={e} style={{background:'#f3f4f8',borderRadius:6,padding:'4px 12px',fontSize:11,fontWeight:600,fontFamily:'monospace',border:'1px solid #e2e5f1'}}>.{e.toLowerCase()}</span>);})}</div>
          <input ref={fRef} type="file" accept=".csv,.tsv,.txt,.xlsx,.xls,.xlsm,.xlsb,.ods,.json,.dta" style={{display:'none'}} onChange={function(e){handleFile(e.target.files[0]);}}/>
          {fLoad?(<div style={{display:'flex',alignItems:'center',justifyContent:'center',gap:12}}><div style={{width:22,height:22,borderRadius:'50%',border:'3px solid #e0e7ff',borderTopColor:'#4f46e5',animation:'spin 0.7s linear infinite'}}/><span style={{color:'#6b7194'}}>Reading...</span></div>):(<button onClick={function(){fRef.current&&fRef.current.click();}} style={{padding:'12px 32px',borderRadius:10,border:'none',background:'#4f46e5',color:'#fff',fontSize:15,fontWeight:600,cursor:'pointer'}}>Choose File</button>)}
          <p style={{color:'#6b7194',fontSize:12,marginTop:16}}>or drag and drop</p></div>
          {fErr&&<div style={{marginTop:16,padding:'12px 18px',borderRadius:10,background:'#fef2f2',border:'1px solid #fecaca',color:'#b91c1c',fontSize:13,textAlign:'left'}}>{fErr}</div>}</Card>)}

        {/* ══════ CONFIGURE ══════ */}
        {step===1&&(<div>
          <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',marginBottom:14}}>
            <div><h2 style={{margin:0,fontSize:20}}>Configure DEA Model</h2><span style={{fontSize:13,color:'#6b7194'}}>{fName} — {raw?raw.length:0} obs · {hdr.length} variables ({numH.length} numeric)</span></div>
            <button onClick={function(){setStep(0);setRaw(null);setHdr([]);setInpV([]);setOutV([]);setGrpV([]);setOptV([]);setFilters([]);}} style={{padding:'4px 12px',borderRadius:6,border:'1px solid #e2e5f1',background:'#fff',cursor:'pointer',fontSize:11,color:'#dc2626'}}>Change File</button>
          </div>
          {sheets.length>1&&(<div style={{background:'#e0e7ff',borderRadius:10,padding:'10px 16px',marginBottom:14,display:'flex',alignItems:'center',gap:8,flexWrap:'wrap'}}><span style={{fontSize:12,fontWeight:600,color:'#3730a3'}}>Sheets:</span>{sheets.map(function(sn){return (<button key={sn} onClick={function(){switchSh(sn);}} style={{padding:'3px 12px',borderRadius:6,border:selSh===sn?'1px solid #4f46e5':'1px solid transparent',background:selSh===sn?'#fff':'rgba(255,255,255,0.5)',color:selSh===sn?'#4f46e5':'#6b7194',fontSize:12,cursor:'pointer',fontWeight:selSh===sn?600:400}}>{sn}</button>);})}</div>)}

          {/* ── CURRENT SELECTION SUMMARY (only when something is selected) ── */}
          {(inpV.length>0||outV.length>0||grpV.length>0||optV.length>0)&&(<Card style={{marginBottom:14,background:'#f8f9fc',border:'2px solid #e0e7ff'}}>
            <h3 style={{margin:'0 0 10px',fontSize:14,fontWeight:700,color:'#3730a3'}}>Current Variable Selection</h3>
            {[{t:'Inputs',v:inpV,c:'#3b82f6',s:setInpV},{t:'Outputs',v:outV,c:'#059669',s:setOutV},{t:'Disaggregation',v:grpV,c:'#d97706',s:setGrpV},{t:'Optimization',v:optV,c:'#7c3aed',s:setOptV}].map(function(sec){return sec.v.length===0?null:(<div key={sec.t} style={{marginBottom:6}}>
              <span style={{fontSize:11,fontWeight:600,color:sec.c,marginRight:8}}>{sec.t}:</span>
              {sec.v.map(function(vn){return (<SelTag key={vn} name={vn} color={sec.c} onRemove={function(){tog(vn,sec.v,sec.s);}}/>);})}
            </div>);})}
          </Card>)}

          {/* ── INPUT METHOD SELECTOR ── */}
          <div style={{display:'flex',gap:8,marginBottom:14}}>
            <button onClick={function(){setInputMethod('click');}} style={{flex:1,padding:'10px 16px',borderRadius:10,border:inputMethod==='click'?'2px solid #4f46e5':'1px solid #e2e5f1',background:inputMethod==='click'?'#e0e7ff':'#fff',color:inputMethod==='click'?'#3730a3':'#6b7194',fontSize:13,fontWeight:inputMethod==='click'?700:400,cursor:'pointer',textAlign:'center'}}>
              <div style={{fontSize:16,marginBottom:4}}>🖱️</div>Option A: Click to Select Variables
            </button>
            <button onClick={function(){setInputMethod('type');}} style={{flex:1,padding:'10px 16px',borderRadius:10,border:inputMethod==='type'?'2px solid #4f46e5':'1px solid #e2e5f1',background:inputMethod==='type'?'#e0e7ff':'#fff',color:inputMethod==='type'?'#3730a3':'#6b7194',fontSize:13,fontWeight:inputMethod==='type'?700:400,cursor:'pointer',textAlign:'center'}}>
              <div style={{fontSize:16,marginBottom:4}}>⌨️</div>Option B: Type Variable Names (comma-separated)
            </button>
          </div>

          {/* ── OPTION A: CLICK SELECTION ── */}
          {inputMethod==='click'&&(<div>
            <input placeholder={"Search among "+hdr.length+" variables..."} value={srch} onChange={function(e){setSrch(e.target.value);}} style={{width:'100%',padding:'10px 16px',borderRadius:10,border:'1px solid #e2e5f1',background:'#fff',fontSize:14,outline:'none',marginBottom:10,boxSizing:'border-box'}}/>
            {srch&&<p style={{fontSize:11,color:'#6b7194',margin:'0 0 10px'}}>Showing {filtH.length} of {hdr.length} matching "{srch}"</p>}
            <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:14}}>
              {[{t:'Input Variables',d:'Resources consumed',v:inpV,s:setInpV,c:'#3b82f6',oth:outV,os:setOutV,isNum:true,pool:null},
                {t:'Output Variables',d:'Performance outcomes',v:outV,s:setOutV,c:'#059669',oth:inpV,os:setInpV,isNum:true,pool:null},
                {t:'Disaggregation',d:'Categorical variables only (province, type, etc.)',v:grpV,s:setGrpV,c:'#d97706',oth:null,os:null,isNum:false,pool:'categorical'},
                {t:'Optimization',d:'Actual vs optimal (from selected inputs)',v:optV,s:setOptV,c:'#7c3aed',oth:null,os:null,isNum:true,pool:'inputs'}
              ].map(function(sec){
                var av;if(sec.pool==='inputs')av=inpV;else if(sec.pool==='categorical'){av=srch?filtH.filter(function(h){return catH.indexOf(h)>=0;}):catH;}else if(srch)av=filtH.filter(function(h){return sec.isNum?numH.indexOf(h)>=0:true;});else av=sec.isNum?numH:hdr;
                var isExp=expandedSections[sec.t];var maxH=isExp?'2000px':'180px';var showExp=av.length>15;
                return (<Card key={sec.t}>
                  <div style={{display:'flex',alignItems:'center',gap:8,marginBottom:6}}><div style={{width:8,height:8,borderRadius:'50%',background:sec.c}}/><h3 style={{margin:0,fontSize:14,fontWeight:600}}>{sec.t}</h3><span style={{marginLeft:'auto',fontSize:11,color:sec.c}}>{sec.v.length} / {av.length}</span></div>
                  <p style={{fontSize:11,color:'#6b7194',margin:'0 0 8px'}}>{sec.d}</p>
                  {sec.pool==='inputs'&&inpV.length===0&&<p style={{fontSize:11,color:'#d97706',margin:'0 0 8px',fontStyle:'italic'}}>Select input variables first</p>}
                  <div style={{maxHeight:maxH,overflowY:'auto',display:'flex',flexWrap:'wrap',gap:5}}>{av.map(function(h){return (<VarPill key={h} label={h} selected={sec.v.indexOf(h)>=0} color={sec.c} onClick={function(){tog(h,sec.v,sec.s);if(sec.oth&&sec.oth.indexOf(h)>=0)sec.os(function(p){return p.filter(function(x){return x!==h;});});}}/>);})}</div>
                  {showExp&&(<button onClick={function(){setExpandedSections(function(prev){var n={};Object.keys(prev).forEach(function(k){n[k]=prev[k];});n[sec.t]=!prev[sec.t];return n;});}} style={{marginTop:6,padding:'3px 12px',borderRadius:6,border:'1px solid #e2e5f1',background:'#f8f9fc',color:'#6b7194',fontSize:11,cursor:'pointer',width:'100%',textAlign:'center'}}>{isExp?'Show less':'Show all '+av.length+' variables'}</button>)}
                </Card>);
              })}
            </div>
          </div>)}

          {/* ── OPTION B: TYPE NAMES ── */}
          {inputMethod==='type'&&(<Card>
            <h3 style={{margin:'0 0 12px',fontSize:14,fontWeight:600}}>Type variable names separated by commas, then press Enter or click Add</h3>
            <div style={{display:'grid',gridTemplateColumns:'1fr',gap:12}}>
              {[{l:'Input Variables',k:'inp',c:'#3b82f6',set:setInpV,valid:numH},
                {l:'Output Variables',k:'out',c:'#059669',set:setOutV,valid:numH},
                {l:'Disaggregation Variables (categorical only)',k:'grp',c:'#d97706',set:setGrpV,valid:catH},
                {l:'Optimization Variables',k:'opt',c:'#7c3aed',set:setOptV,valid:inpV}
              ].map(function(x){return (<div key={x.k}>
                <label style={{fontSize:12,fontWeight:600,color:x.c,marginBottom:4,display:'block'}}>{x.l}</label>
                <div style={{display:'flex',gap:8}}>
                  <input placeholder={"var1, var2, var3, ..."} value={commaInput[x.k]} onChange={function(e){setCommaInput(function(prev){var n={};Object.keys(prev).forEach(function(kk){n[kk]=prev[kk];});n[x.k]=e.target.value;return n;});}} onKeyDown={function(e){if(e.key==='Enter'){applyComma(commaInput[x.k],x.set,x.valid);setCommaInput(function(prev){var n={};Object.keys(prev).forEach(function(kk){n[kk]=prev[kk];});n[x.k]='';return n;});}}} style={{flex:1,padding:'8px 12px',borderRadius:8,border:'1px solid #e2e5f1',fontSize:13,outline:'none'}}/>
                  <button onClick={function(){applyComma(commaInput[x.k],x.set,x.valid);setCommaInput(function(prev){var n={};Object.keys(prev).forEach(function(kk){n[kk]=prev[kk];});n[x.k]='';return n;});}} style={{padding:'8px 16px',borderRadius:8,border:'1px solid '+x.c,background:'transparent',color:x.c,fontSize:12,fontWeight:600,cursor:'pointer'}}>Add</button>
                </div>
              </div>);})}
            </div>
          </Card>)}

          {/* ── DATA FILTERS (below variables) ── */}
          <Card style={{marginTop:14}}>
            <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',marginBottom:10}}>
              <h3 style={{margin:0,fontSize:14,fontWeight:600}}>Data Filters (optional)</h3>
              <div style={{display:'flex',alignItems:'center',gap:8}}>
                <span style={{fontSize:12,color:'#6b7194'}}>Rows: <strong style={{color:'#1a1d29'}}>{filteredCount}</strong> / {raw?raw.length:0}</span>
                <button onClick={function(){setFilters(function(prev){return prev.concat([{variable:'',values:[]}]);});}} style={{padding:'4px 14px',borderRadius:6,border:'1px solid #4f46e5',background:'transparent',color:'#4f46e5',fontSize:11,fontWeight:600,cursor:'pointer'}}>+ Add Filter</button>
              </div>
            </div>
            {filters.map(function(f,fi){
              var vals=f.variable?uniqueVals(f.variable):[];
              return (<div key={fi} style={{display:'flex',gap:8,alignItems:'flex-start',marginBottom:8,padding:10,background:'#f3f4f8',borderRadius:10}}>
                <select value={f.variable} onChange={function(e){setFilters(function(prev){var n=prev.slice();n[fi]={variable:e.target.value,values:[]};return n;});}} style={{padding:'6px 8px',borderRadius:6,border:'1px solid #e2e5f1',fontSize:12,minWidth:140}}>
                  <option value="">Select variable...</option>
                  {hdr.map(function(h){return (<option key={h} value={h}>{h}</option>);})}
                </select>
                <div style={{flex:1,display:'flex',flexWrap:'wrap',gap:4,maxHeight:120,overflowY:'auto'}}>
                  {vals.map(function(val){var sel=f.values.indexOf(val)>=0;return (<button key={val} onClick={function(){setFilters(function(prev){var n=prev.slice();var cur=n[fi].values.slice();if(sel)cur=cur.filter(function(x){return x!==val;});else cur.push(val);n[fi]={variable:n[fi].variable,values:cur};return n;});}} style={{padding:'3px 10px',borderRadius:6,border:sel?'1.5px solid #4f46e5':'1px solid #e2e5f1',background:sel?'#e0e7ff':'#fff',color:sel?'#4f46e5':'#6b7194',fontSize:11,cursor:'pointer',fontWeight:sel?600:400}}>{val}</button>);})}
                </div>
                <button onClick={function(){setFilters(function(prev){return prev.filter(function(_,i){return i!==fi;});});}} style={{padding:'4px 8px',borderRadius:6,border:'1px solid #fecaca',background:'transparent',color:'#dc2626',fontSize:11,cursor:'pointer'}}>Remove</button>
              </div>);
            })}
            {filters.length===0&&<p style={{fontSize:12,color:'#6b7194',margin:0}}>No filters applied. All rows will be used. Add filters to subset data (e.g., school_type = PS).</p>}
          </Card>

          {/* ── SUPER-EFFICIENCY ── */}
          <Card style={{marginTop:14,display:'flex',alignItems:'center',gap:16,flexWrap:'wrap'}}>
            <label style={{display:'flex',alignItems:'center',gap:10,cursor:'pointer',fontSize:14}}>
              <div onClick={function(){setDoSE(!doSE);}} style={{width:44,height:24,borderRadius:12,background:doSE?'#4f46e5':'#e2e5f1',position:'relative',cursor:'pointer'}}><div style={{width:18,height:18,borderRadius:'50%',background:'#fff',position:'absolute',top:3,left:doSE?23:3,transition:'left 0.2s',boxShadow:'0 1px 3px rgba(0,0,0,0.2)'}}/></div>
              <span style={{fontWeight:500}}>Super-Efficiency Outlier Detection (Andersen & Petersen, 1993)</span>
            </label>
            {doSE&&(<div style={{display:'flex',alignItems:'center',gap:12,flexWrap:'wrap'}}>
              <div style={{display:'flex',alignItems:'center',gap:6}}><span style={{fontSize:12,color:'#6b7194'}}>Extreme threshold:</span><input type="number" value={seTh} onChange={function(e){setSeTh(parseFloat(e.target.value)||1.5);}} step={0.1} min={1.1} style={{width:60,padding:'4px 8px',borderRadius:6,border:'1px solid #e2e5f1',fontSize:13,textAlign:'center'}}/></div>
              <div style={{display:'flex',alignItems:'center',gap:6}}><span style={{fontSize:12,color:'#6b7194'}}>Clean cutoff:</span>{[1.2,1.5].map(function(v){return (<button key={v} onClick={function(){setCleanCutoff(v);}} style={{padding:'4px 14px',borderRadius:8,border:cleanCutoff===v?'2px solid #4f46e5':'1px solid #e2e5f1',background:cleanCutoff===v?'#e0e7ff':'#fff',color:cleanCutoff===v?'#4f46e5':'#6b7194',fontSize:12,fontWeight:cleanCutoff===v?700:400,cursor:'pointer'}}>{"SE > "+v}</button>);})}</div>
            </div>)}
            <p style={{fontSize:11,color:'#6b7194',margin:0,flexBasis:'100%'}}>Clean frontier re-runs DEA excluding DMUs above the cutoff.</p>
          </Card>

          {/* ── RUN BUTTON ── */}
          <div style={{marginTop:24,textAlign:'center'}}>
            <button onClick={run} disabled={!canRun} style={{padding:'14px 48px',borderRadius:12,border:'none',background:canRun?'#4f46e5':'#e2e5f1',color:canRun?'#fff':'#6b7194',fontSize:16,fontWeight:700,cursor:canRun?'pointer':'not-allowed'}}>Run DEA Analysis</button>
            {!canRun&&<p style={{fontSize:12,color:'#dc2626',marginTop:8}}>Select at least 1 input and 1 output variable</p>}
          </div>
        </div>)}

        {/* ══════ RUNNING ══════ */}
        {step===2&&(<Card style={{textAlign:'center',padding:48}}><div style={{width:60,height:60,margin:'0 auto 20px',borderRadius:'50%',border:'3px solid #e0e7ff',borderTopColor:'#4f46e5',animation:'spin 1s linear infinite'}}/><h3 style={{margin:'0 0 8px',fontSize:18}}>Running Analysis</h3><p style={{color:'#6b7194',fontSize:14}}>{prog}</p></Card>)}

        {/* ══════ RESULTS ══════ */}
        {step===3&&res&&(<div>
          <div style={{display:'flex',gap:2,marginBottom:20,background:'#f3f4f8',borderRadius:12,padding:4,overflowX:'auto'}}>
            {['Summary','Efficiency','Slack & Excess','Disaggregation','Optimization','Data'].map(function(l){var id=l.toLowerCase().replace(/[^a-z]/g,'');return (<button key={id} onClick={function(){setTab(id);}} style={{padding:'8px 16px',borderRadius:8,border:'none',background:tab===id?'#fff':'transparent',color:tab===id?'#4f46e5':'#6b7194',fontSize:12,fontWeight:tab===id?600:400,cursor:'pointer',whiteSpace:'nowrap'}}>{l}</button>);})}
          </div>

          {tab==='summary'&&(<div>
            <SectionLabel text="Full Sample Results" color="#4f46e5"/><ResultBlock r={res.full} color="#4f46e5"/>
            <div style={{background:'#e0e7ff',borderRadius:10,padding:14,marginTop:14,fontSize:12,color:'#3730a3'}}><strong>Sample: </strong>{res.nTotal+" total rows → "+res.nDroppedMissing+" dropped (missing/invalid) → "+res.full.n+" valid DMUs used"}<br/><strong>Dimensionality: </strong>{"n="+res.full.n+", rule="+Math.max(res.full.m*res.full.s,3*(res.full.m+res.full.s))+", ratio="+(res.full.n/Math.max(res.full.m*res.full.s,3*(res.full.m+res.full.s))).toFixed(1)+"x"}<br/><strong>Inputs ({res.full.m}): </strong>{res.full.inputVars.slice().sort().join(', ')} <br/><strong>Outputs ({res.full.s}): </strong>{res.full.outputVars.slice().sort().join(', ')}<br/><span style={{fontSize:10,opacity:0.7}}>Results are order-independent: only the set of variables and the sample (N) determine efficiency scores. If N differs between runs, a different variable set was used.</span></div>
            {res.hasSE&&res.superRes&&(<div style={{marginTop:24}}><SectionLabel text="Super-Efficiency — Andersen & Petersen (1993)" color="#6366f1"/>
              <div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:12,marginBottom:16}}><MetricCard icon="⭐" label="Efficient DMUs" value={res.superRes.nEfficient} color="#4f46e5"/><MetricCard icon="🟡" label="Flagged (1.2 < SE)" value={res.superRes.flagged.length} color="#d97706"/><MetricCard icon="🔴" label={"Extreme (SE > "+res.superRes.threshold+")"} value={res.superRes.extreme.length} color="#dc2626"/><MetricCard icon="🧹" label="Clean Cutoff" value={"SE > "+res.cutoff} color="#6366f1"/></div>
              <Card style={{marginBottom:14}}><Hist values={Array.from(res.superRes.scores).filter(function(v){return Math.abs(v-1)<0.01||v>1;})} title="Super-Efficiency Distribution" color="#6366f1"/></Card>
              {(res.superRes.extreme.length>0||res.superRes.flagged.length>0)&&(<Card><h3 style={{margin:'0 0 10px',fontSize:14}}>Outliers</h3><Tbl columns={hdr.filter(function(h){return numH.indexOf(h)<0;}).slice(0,2).map(function(h){return{key:h,label:h};}).concat([{key:'score',label:'Super-Eff',dec:4},{key:'type',label:'Status'}])} data={res.superRes.extreme.map(function(e){var o={};Object.keys(e.data).forEach(function(k){o[k]=e.data[k];});o.score=e.score;o.type='Extreme';return o;}).concat(res.superRes.flagged.map(function(e){var o={};Object.keys(e.data).forEach(function(k){o[k]=e.data[k];});o.score=e.score;o.type='Flagged';return o;})).sort(function(a,b){return b.score-a.score;})}/></Card>)}
            </div>)}
            {res.clean&&(<div style={{marginTop:24}}><SectionLabel text={"Clean Frontier ("+res.clean.nDropped+" outliers removed)"} color="#059669"/><ResultBlock r={res.clean} color="#059669"/></div>)}
          </div>)}

          {tab==='efficiency'&&(<div><SectionLabel text="Full Sample" color="#4f46e5"/><EffBlock r={res.full} hdr={hdr} numH={numH}/>{res.clean&&(<div style={{marginTop:24}}><SectionLabel text={"Clean Frontier ("+res.clean.nDropped+" removed)"} color="#059669"/><EffBlock r={res.clean} hdr={hdr} numH={numH}/></div>)}</div>)}
          {tab==='slackexcess'&&(<div><SectionLabel text="Full Sample" color="#4f46e5"/><SlackBlock r={res.full}/>{res.clean&&(<div style={{marginTop:24}}><SectionLabel text={"Clean ("+res.clean.nDropped+" removed)"} color="#059669"/><SlackBlock r={res.clean}/></div>)}</div>)}
          {tab==='disaggregation'&&(<div><SectionLabel text="Full Sample" color="#4f46e5"/><DisaggBlock r={res.full}/>{res.clean&&(<div style={{marginTop:24}}><SectionLabel text={"Clean ("+res.clean.nDropped+" removed)"} color="#059669"/><DisaggBlock r={res.clean}/></div>)}</div>)}
          {tab==='optimization'&&(<div><SectionLabel text="Full Sample" color="#4f46e5"/><OptimBlock r={res.full}/>{res.clean&&(<div style={{marginTop:24}}><SectionLabel text={"Clean ("+res.clean.nDropped+" removed)"} color="#059669"/><OptimBlock r={res.clean}/></div>)}</div>)}
          {tab==='data'&&(<Card><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:12}}><h3 style={{margin:0,fontSize:15}}>Full Sample ({res.full.schoolData.length})</h3><button onClick={function(){var cols=hdr.slice(0,5).concat(['eff_crs','eff_vrs','scale_eff']).concat(res.full.inputVars.map(function(v){return'pct_excess_'+v;}));var csv=[cols.join(',')].concat(res.full.schoolData.map(function(r2){return cols.map(function(c2){var v=r2[c2];return typeof v==='number'?v.toFixed(4):('"'+(v||'')+'"');}).join(',');})).join('\n');var a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='dea_results.csv';a.click();}} style={{padding:'8px 20px',borderRadius:8,border:'1px solid #4f46e5',background:'transparent',color:'#4f46e5',fontSize:12,fontWeight:600,cursor:'pointer'}}>Download CSV</button></div>
            <Tbl columns={hdr.filter(function(h){return numH.indexOf(h)<0;}).slice(0,3).map(function(h){return{key:h,label:h};}).concat([{key:'eff_crs',label:'CRS',dec:4},{key:'eff_vrs',label:'VRS',dec:4},{key:'scale_eff',label:'Scale',dec:4}]).concat(res.full.inputVars.map(function(v){return{key:'pct_excess_'+v,label:'%E '+v.slice(0,12),dec:1};}))} data={res.full.schoolData} pp={15}/>
            {res.clean&&(<div style={{marginTop:20}}><SectionLabel text={"Clean ("+res.clean.schoolData.length+")"} color="#059669"/><Tbl columns={hdr.filter(function(h){return numH.indexOf(h)<0;}).slice(0,3).map(function(h){return{key:h,label:h};}).concat([{key:'eff_crs',label:'CRS',dec:4},{key:'eff_vrs',label:'VRS',dec:4},{key:'scale_eff',label:'Scale',dec:4}]).concat(res.clean.inputVars.map(function(v){return{key:'pct_excess_'+v,label:'%E '+v.slice(0,12),dec:1};}))} data={res.clean.schoolData} pp={15}/></div>)}</Card>)}

          <div style={{marginTop:24,textAlign:'center'}}><button onClick={function(){setStep(1);setRes(null);}} style={{padding:'10px 28px',borderRadius:10,border:'1px solid #e2e5f1',background:'#fff',fontSize:13,cursor:'pointer'}}>Back to Configuration</button></div>
        </div>)}
      </div>

      {/* FOOTER */}
      <footer style={{textAlign:'center',padding:'24px 32px',fontSize:11,color:'#6b7194',borderTop:'1px solid #e2e5f1',marginTop:20,lineHeight:1.8}}>
        CRS (CCR) — Charnes, Cooper, and Rhodes (1978) · VRS (BCC) — Banker, Charnes, and Cooper (1984)<br/>
        Super-Efficiency — Andersen and Petersen (1993) · Stata DEA command — Ji and Lee (2010)<br/>
        Platform developed by Karina Acevedo Gonzalez @kacego9 · 2026
      </footer>
    </div>
  );
}
